version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      time: "17:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "aws-sdk-php"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
