<?php
require_once __DIR__ . '/../../common/coreHead.php';

header("Content-Security-Policy: default-src 'none';" .
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://assets.adam-rms.com https://cdnjs.cloudflare.com  https://static.cloudflareinsights.com ;".
    //          We have laods of inline JS                                  Libs                                Google webmaster tools
    "style-src 'unsafe-inline' 'self' https://assets.adam-rms.com https://cdnjs.cloudflare.com https://fonts.googleapis.com;".
    //          We have loads of inline CSS                 Libs                        GFonts
    "font-src 'self' data: https://assets.adam-rms.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com;" .
    //                                               Loading in google fonts     more gfonts               Fonts from libs like fontawesome
    "manifest-src 'self' https://*.adam-rms.com;" .
    //          Show images on mobile devices like favicons
    "img-src 'self' data: blob: https://assets.adam-rms.com https://cdnjs.cloudflare.com https://*.adam-rms.com https://cloudflareinsights.com https://*.backblazeb2.com;".
    //                                                    Uploads    Images from libs                 Images                CF Analytics                                            Training                Uploads
    "connect-src 'self' https://*.adam-rms.com https://sentry.io https://cloudflareinsights.com;".
    //                  File uploads                      Error reporting     CF Analytics
    "frame-src ;".
    "object-src 'self' blob:;".
    //          Inline PDFs generated by the system
    "frame-ancestors 'self';");


$DBLIB->where("instances_deleted",0);
$DBLIB->where("instances_publicConfig",NULL, "IS NOT");
$instances = $DBLIB->get("instances");
$PAGEDATA['INSTANCE'] = false;
foreach ($instances as $instance) {
    $instance['publicData'] = json_decode($instance['instances_publicConfig'],true);
    if (!is_array($instance['publicData']['customDomains'])) continue;
    foreach ($instance['publicData']['customDomains'] as $domain) {
        if (trim($_SERVER['SERVER_NAME']) == $domain) {
            $PAGEDATA['INSTANCE'] = $instance;
            break;
        }
    }
}
if (!$PAGEDATA['INSTANCE'] or !isset($PAGEDATA['INSTANCE']['publicData']['enabled']) or !$PAGEDATA['INSTANCE']['publicData']['enabled']) die("404");

$PAGEDATA['INSTANCE']['FILES'] = $bCMS->s3List(15, $PAGEDATA['INSTANCE']['instances_id']);