import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  contributorSidebar: [
    {
      type: "link",
      label: "GitHub",
      href: "https://github.com/adam-rms",
    },
    {
      type: "autogenerated",
      dirName: "contributor",
    },
  ],
  hostingSidebar: [
    {
      type: "autogenerated",
      dirName: "hosting",
    },
  ],
  userGuideSidebar: [
    {
      type: "link",
      label: "Login",
      href: "https://dash.adam-rms.com",
    },
    {
      type: "autogenerated",
      dirName: "user-guide",
    },
  ],
};

export default sidebars;
