/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  contributorSidebar: [
    {
      type: "link",
      label: "Github", // The link label
      href: "https://github.com/adam-rms", // The external URL
    },
    {
      type: "autogenerated",
      dirName: "contributor",
    },
  ],
  hostingSidebar: [
    {
      type: "autogenerated",
      dirName: "hosting",
    },
  ],
  userGuideSidebar: [
    {
      type: "link",
      label: "Login",
      href: "https://dash.adam-rms.com",
    },
    {
      type: "autogenerated",
      dirName: "user-guide",
    },
  ],
};
